package com.zyy.blog.modules.sys.entity;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_user_id
     *
     * @mbggenerated
     */
    private Integer articleUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_parent_category_id
     *
     * @mbggenerated
     */
    private Integer articleParentCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_child_category_id
     *
     * @mbggenerated
     */
    private Integer articleChildCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_tag_ids
     *
     * @mbggenerated
     */
    private String articleTagIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_view_count
     *
     * @mbggenerated
     */
    private Integer articleViewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_comment_count
     *
     * @mbggenerated
     */
    private Integer articleCommentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_like_count
     *
     * @mbggenerated
     */
    private Integer articleLikeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_post_time
     *
     * @mbggenerated
     */
    private Date articlePostTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_update_time
     *
     * @mbggenerated
     */
    private Date articleUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_is_comment
     *
     * @mbggenerated
     */
    private Integer articleIsComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_status
     *
     * @mbggenerated
     */
    private Integer articleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_order
     *
     * @mbggenerated
     */
    private Integer articleOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_user_id
     *
     * @return the value of article.article_user_id
     *
     * @mbggenerated
     */
    public Integer getArticleUserId() {
        return articleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_user_id
     *
     * @param articleUserId the value for article.article_user_id
     *
     * @mbggenerated
     */
    public void setArticleUserId(Integer articleUserId) {
        this.articleUserId = articleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_parent_category_id
     *
     * @return the value of article.article_parent_category_id
     *
     * @mbggenerated
     */
    public Integer getArticleParentCategoryId() {
        return articleParentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_parent_category_id
     *
     * @param articleParentCategoryId the value for article.article_parent_category_id
     *
     * @mbggenerated
     */
    public void setArticleParentCategoryId(Integer articleParentCategoryId) {
        this.articleParentCategoryId = articleParentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_child_category_id
     *
     * @return the value of article.article_child_category_id
     *
     * @mbggenerated
     */
    public Integer getArticleChildCategoryId() {
        return articleChildCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_child_category_id
     *
     * @param articleChildCategoryId the value for article.article_child_category_id
     *
     * @mbggenerated
     */
    public void setArticleChildCategoryId(Integer articleChildCategoryId) {
        this.articleChildCategoryId = articleChildCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_tag_ids
     *
     * @return the value of article.article_tag_ids
     *
     * @mbggenerated
     */
    public String getArticleTagIds() {
        return articleTagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_tag_ids
     *
     * @param articleTagIds the value for article.article_tag_ids
     *
     * @mbggenerated
     */
    public void setArticleTagIds(String articleTagIds) {
        this.articleTagIds = articleTagIds == null ? null : articleTagIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_view_count
     *
     * @return the value of article.article_view_count
     *
     * @mbggenerated
     */
    public Integer getArticleViewCount() {
        return articleViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_view_count
     *
     * @param articleViewCount the value for article.article_view_count
     *
     * @mbggenerated
     */
    public void setArticleViewCount(Integer articleViewCount) {
        this.articleViewCount = articleViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_comment_count
     *
     * @return the value of article.article_comment_count
     *
     * @mbggenerated
     */
    public Integer getArticleCommentCount() {
        return articleCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_comment_count
     *
     * @param articleCommentCount the value for article.article_comment_count
     *
     * @mbggenerated
     */
    public void setArticleCommentCount(Integer articleCommentCount) {
        this.articleCommentCount = articleCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_like_count
     *
     * @return the value of article.article_like_count
     *
     * @mbggenerated
     */
    public Integer getArticleLikeCount() {
        return articleLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_like_count
     *
     * @param articleLikeCount the value for article.article_like_count
     *
     * @mbggenerated
     */
    public void setArticleLikeCount(Integer articleLikeCount) {
        this.articleLikeCount = articleLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_post_time
     *
     * @return the value of article.article_post_time
     *
     * @mbggenerated
     */
    public Date getArticlePostTime() {
        return articlePostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_post_time
     *
     * @param articlePostTime the value for article.article_post_time
     *
     * @mbggenerated
     */
    public void setArticlePostTime(Date articlePostTime) {
        this.articlePostTime = articlePostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_update_time
     *
     * @return the value of article.article_update_time
     *
     * @mbggenerated
     */
    public Date getArticleUpdateTime() {
        return articleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_update_time
     *
     * @param articleUpdateTime the value for article.article_update_time
     *
     * @mbggenerated
     */
    public void setArticleUpdateTime(Date articleUpdateTime) {
        this.articleUpdateTime = articleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_is_comment
     *
     * @return the value of article.article_is_comment
     *
     * @mbggenerated
     */
    public Integer getArticleIsComment() {
        return articleIsComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_is_comment
     *
     * @param articleIsComment the value for article.article_is_comment
     *
     * @mbggenerated
     */
    public void setArticleIsComment(Integer articleIsComment) {
        this.articleIsComment = articleIsComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_status
     *
     * @return the value of article.article_status
     *
     * @mbggenerated
     */
    public Integer getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_status
     *
     * @param articleStatus the value for article.article_status
     *
     * @mbggenerated
     */
    public void setArticleStatus(Integer articleStatus) {
        this.articleStatus = articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_order
     *
     * @return the value of article.article_order
     *
     * @mbggenerated
     */
    public Integer getArticleOrder() {
        return articleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_order
     *
     * @param articleOrder the value for article.article_order
     *
     * @mbggenerated
     */
    public void setArticleOrder(Integer articleOrder) {
        this.articleOrder = articleOrder;
    }
}