package com.zyy.blog.modules.sys.entity;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_pid
     *
     * @mbggenerated
     */
    private Integer categoryPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_description
     *
     * @mbggenerated
     */
    private String categoryDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_order
     *
     * @mbggenerated
     */
    private Integer categoryOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_icon
     *
     * @mbggenerated
     */
    private String categoryIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_status
     *
     * @mbggenerated
     */
    private Integer categoryStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_pid
     *
     * @return the value of category.category_pid
     *
     * @mbggenerated
     */
    public Integer getCategoryPid() {
        return categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_pid
     *
     * @param categoryPid the value for category.category_pid
     *
     * @mbggenerated
     */
    public void setCategoryPid(Integer categoryPid) {
        this.categoryPid = categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_description
     *
     * @return the value of category.category_description
     *
     * @mbggenerated
     */
    public String getCategoryDescription() {
        return categoryDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_description
     *
     * @param categoryDescription the value for category.category_description
     *
     * @mbggenerated
     */
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription == null ? null : categoryDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_order
     *
     * @return the value of category.category_order
     *
     * @mbggenerated
     */
    public Integer getCategoryOrder() {
        return categoryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_order
     *
     * @param categoryOrder the value for category.category_order
     *
     * @mbggenerated
     */
    public void setCategoryOrder(Integer categoryOrder) {
        this.categoryOrder = categoryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_icon
     *
     * @return the value of category.category_icon
     *
     * @mbggenerated
     */
    public String getCategoryIcon() {
        return categoryIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_icon
     *
     * @param categoryIcon the value for category.category_icon
     *
     * @mbggenerated
     */
    public void setCategoryIcon(String categoryIcon) {
        this.categoryIcon = categoryIcon == null ? null : categoryIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_status
     *
     * @return the value of category.category_status
     *
     * @mbggenerated
     */
    public Integer getCategoryStatus() {
        return categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_status
     *
     * @param categoryStatus the value for category.category_status
     *
     * @mbggenerated
     */
    public void setCategoryStatus(Integer categoryStatus) {
        this.categoryStatus = categoryStatus;
    }
}