package com.zyy.blog.modules.sys.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_pid
     *
     * @mbggenerated
     */
    private Integer commentPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_pname
     *
     * @mbggenerated
     */
    private String commentPname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_article_id
     *
     * @mbggenerated
     */
    private Integer commentArticleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_author_name
     *
     * @mbggenerated
     */
    private String commentAuthorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_author_email
     *
     * @mbggenerated
     */
    private String commentAuthorEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_author_url
     *
     * @mbggenerated
     */
    private String commentAuthorUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbggenerated
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_agent
     *
     * @mbggenerated
     */
    private String commentAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_ip
     *
     * @mbggenerated
     */
    private String commentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_create_time
     *
     * @mbggenerated
     */
    private Date commentCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_role
     *
     * @mbggenerated
     */
    private Integer commentRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_status
     *
     * @mbggenerated
     */
    private Integer commentStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_pid
     *
     * @return the value of comment.comment_pid
     *
     * @mbggenerated
     */
    public Integer getCommentPid() {
        return commentPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_pid
     *
     * @param commentPid the value for comment.comment_pid
     *
     * @mbggenerated
     */
    public void setCommentPid(Integer commentPid) {
        this.commentPid = commentPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_pname
     *
     * @return the value of comment.comment_pname
     *
     * @mbggenerated
     */
    public String getCommentPname() {
        return commentPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_pname
     *
     * @param commentPname the value for comment.comment_pname
     *
     * @mbggenerated
     */
    public void setCommentPname(String commentPname) {
        this.commentPname = commentPname == null ? null : commentPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_article_id
     *
     * @return the value of comment.comment_article_id
     *
     * @mbggenerated
     */
    public Integer getCommentArticleId() {
        return commentArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_article_id
     *
     * @param commentArticleId the value for comment.comment_article_id
     *
     * @mbggenerated
     */
    public void setCommentArticleId(Integer commentArticleId) {
        this.commentArticleId = commentArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_author_name
     *
     * @return the value of comment.comment_author_name
     *
     * @mbggenerated
     */
    public String getCommentAuthorName() {
        return commentAuthorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_author_name
     *
     * @param commentAuthorName the value for comment.comment_author_name
     *
     * @mbggenerated
     */
    public void setCommentAuthorName(String commentAuthorName) {
        this.commentAuthorName = commentAuthorName == null ? null : commentAuthorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_author_email
     *
     * @return the value of comment.comment_author_email
     *
     * @mbggenerated
     */
    public String getCommentAuthorEmail() {
        return commentAuthorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_author_email
     *
     * @param commentAuthorEmail the value for comment.comment_author_email
     *
     * @mbggenerated
     */
    public void setCommentAuthorEmail(String commentAuthorEmail) {
        this.commentAuthorEmail = commentAuthorEmail == null ? null : commentAuthorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_author_url
     *
     * @return the value of comment.comment_author_url
     *
     * @mbggenerated
     */
    public String getCommentAuthorUrl() {
        return commentAuthorUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_author_url
     *
     * @param commentAuthorUrl the value for comment.comment_author_url
     *
     * @mbggenerated
     */
    public void setCommentAuthorUrl(String commentAuthorUrl) {
        this.commentAuthorUrl = commentAuthorUrl == null ? null : commentAuthorUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     *
     * @mbggenerated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     *
     * @mbggenerated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_agent
     *
     * @return the value of comment.comment_agent
     *
     * @mbggenerated
     */
    public String getCommentAgent() {
        return commentAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_agent
     *
     * @param commentAgent the value for comment.comment_agent
     *
     * @mbggenerated
     */
    public void setCommentAgent(String commentAgent) {
        this.commentAgent = commentAgent == null ? null : commentAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_ip
     *
     * @return the value of comment.comment_ip
     *
     * @mbggenerated
     */
    public String getCommentIp() {
        return commentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_ip
     *
     * @param commentIp the value for comment.comment_ip
     *
     * @mbggenerated
     */
    public void setCommentIp(String commentIp) {
        this.commentIp = commentIp == null ? null : commentIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_create_time
     *
     * @return the value of comment.comment_create_time
     *
     * @mbggenerated
     */
    public Date getCommentCreateTime() {
        return commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_create_time
     *
     * @param commentCreateTime the value for comment.comment_create_time
     *
     * @mbggenerated
     */
    public void setCommentCreateTime(Date commentCreateTime) {
        this.commentCreateTime = commentCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_role
     *
     * @return the value of comment.comment_role
     *
     * @mbggenerated
     */
    public Integer getCommentRole() {
        return commentRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_role
     *
     * @param commentRole the value for comment.comment_role
     *
     * @mbggenerated
     */
    public void setCommentRole(Integer commentRole) {
        this.commentRole = commentRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_status
     *
     * @return the value of comment.comment_status
     *
     * @mbggenerated
     */
    public Integer getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_status
     *
     * @param commentStatus the value for comment.comment_status
     *
     * @mbggenerated
     */
    public void setCommentStatus(Integer commentStatus) {
        this.commentStatus = commentStatus;
    }
}