package com.zyy.blog.modules.sys.entity;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_id
     *
     * @mbggenerated
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_description
     *
     * @mbggenerated
     */
    private String tagDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_status
     *
     * @mbggenerated
     */
    private Integer tagStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_id
     *
     * @return the value of tag.tag_id
     *
     * @mbggenerated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_id
     *
     * @param tagId the value for tag.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_description
     *
     * @return the value of tag.tag_description
     *
     * @mbggenerated
     */
    public String getTagDescription() {
        return tagDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_description
     *
     * @param tagDescription the value for tag.tag_description
     *
     * @mbggenerated
     */
    public void setTagDescription(String tagDescription) {
        this.tagDescription = tagDescription == null ? null : tagDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_status
     *
     * @return the value of tag.tag_status
     *
     * @mbggenerated
     */
    public Integer getTagStatus() {
        return tagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_status
     *
     * @param tagStatus the value for tag.tag_status
     *
     * @mbggenerated
     */
    public void setTagStatus(Integer tagStatus) {
        this.tagStatus = tagStatus;
    }
}